Test:
  SourceCode:
    Skip: true
  PSModule:
    Skip: true
  Module:
    MacOS:
      Skip: true
    Windows:
      Skip: true
  CodeCoverage:
    Skip: true
    PercentTarget: 50
  TestResults:
    Skip: true
  Build:
    Docs:
      Skip: true
