Test:
  SourceCode:
    Skip: true
  PSModule:
    Skip: true
  Module:
    Skip: true
    Windows:
      Skip: true
    MacOS:
      Skip: true
  CodeCoverage:
    Skip: true
    PercentTarget: 50
Build:
  Docs:
    Skip: true
