Test:
  SourceCode:
    Skip: true
  PSModule:
    Skip: true
  Module:
    MacOS:
      Skip: false
    Windows:
      Skip: false
  CodeCoverage:
    Skip: true
    PercentTarget: 50
Build:
  Docs:
    Skip: true
