# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

changelog:
  categories:
    - title: Breaking Changes
      labels:
        - Major
        - Breaking
    - title: New Features
      labels:
        - Minor
        - Feature
        - Improvement
        - Enhancement
    - title: Other Changes
      labels:
        - '*'
