# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - NoRelease
  categories:
    - title: 🌟 Breaking Changes
      labels:
        - Major
        - Breaking
    - title: 🚀 New Features
      labels:
        - Minor
        - Feature
    - title: Other Changes
      labels:
        - '*'
