name: Update coverage report

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  Update-Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update coverage report
        uses: PSModule/GitHub-Script@v1
        with:
          ClientID: ${{ secrets.TEST_APP_CLIENT_ID }}
          PrivateKey: ${{ secrets.TEST_APP_PRIVATE_KEY }}
          Script: |
            . ".\scripts\coverage.ps1"

            $changedFiles = git diff --name-only
            $hasChanges = $null -ne $changedFiles
            "hasChanges=$hasChanges" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

            if (-not $hasChanges) {
              Write-Host 'No automated changes detected'
              return
            }

            # git add .
            # Write-Host '::group::Changed files [$($changedFiles.Count)]'
            # $changedFiles | ForEach-Object { Write-Host $_ }
            # Write-Host '::endgroup::'
            # git commit -m "Auto-generated changes"
            # git push
