name: Nightly run

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Update-Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout GitHub API spec
        uses: actions/checkout@v4
        with:
          repository: github/rest-api-description
          path: rest-api-description

      - name: Update coverage report
        shell: pwsh
        run: |
          Get-ChildItem -Path . -recurse | Select-Object -ExpandProperty FullName | Sort-Object
