name: Nightly Run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  pull-requests: write
  statuses: write

env:
  TEST_APP_CLIENT_ID: ${{ secrets.TEST_APP_CLIENT_ID }}
  TEST_APP_PRIVATE_KEY: ${{ secrets.TEST_APP_PRIVATE_KEY }}
  TEST_FG_PAT: ${{ secrets.TEST_FG_PAT }}
  TEST_PAT: ${{ secrets.TEST_PAT }}

jobs:
  Process-PSModule:
    uses: PSModule/Process-PSModule/.github/workflows/CI.yml@v3
    secrets: inherit
