name: Process-PSModule

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Process-PSModule:
    uses: PSModule/Actions/.github/workflows/Process-PSModule.yml@main
    secrets: inherit
