name: Update coverage report

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  Update-Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize-PSModule
        uses: PSModule/Initialize-PSModule@v1

      - name: Update coverage report
        uses: PSModule/GitHub-Script@v1
        with:
          Script: . '.\scripts\Set-CoverageReport.ps1'
