name: Update coverage report

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  Update-Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update coverage report
        uses: PSModule/GitHub-Script@v1
        with:
          Script: |
            . ".\scripts\Set-CoverageReport.ps1" -Verbose

            LogGroup 'Get-Files' {
              Get-ChildItem -Path . -Recurse | Select-Object -ExpandProperty FullName | Sort-Object
            }

            Get-GitHubContext | Format-Table
            Get-GitHubGitConfig | Format-Table

            git status

            git diff --name-only

            $changedFiles = git diff --name-only
            $hasChanges = $null -ne $changedFiles

            if (-not $hasChanges) {
              Write-Host 'No change detected'
              return
            }

            LogGroup "Changed files [$($changedFiles.Count)]" {
              $changedFiles | ForEach-Object { Write-Host $_ }
            }

            git add .
            git commit -m "Auto-generated changes"
            git push
