name: Update coverage report

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  Update-Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update coverage report
        uses: PSModule/GitHub-Script@v1
        with:
          Script: . '.\scripts\Set-CoverageReport.ps1'
