name: Test [GitHub]

on:
  workflow_dispatch:

permissions: write-all

jobs:
  TestGitHub:
    name: Test GitHub
    if: always()
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ github.token }} # Used for GitHub CLI authentication
    steps:
    - name: Test Authentication using auto PAT
      if: always()
      shell: pwsh
      run: |
        Write-Output '::group::[Debug info] - Environment variables'
        $env:GITHUB_REPOSITORY_NAME = $env:GITHUB_REPOSITORY.Split('/')[1]
        Get-ChildItem Env:
        Write-Output '::endgroup::'

        Write-Output '::group::[Debug info] - File structure'
        Write-Verbose "Current directory: $((Get-Location).Path)" -Verbose
        Write-Verbose "------------------------------------" -Verbose
        Write-Verbose "Current directory content:" -Verbose
        Get-ChildItem -Path . -Recurse | Select-Object -ExpandProperty FullName | Sort-Object
        Write-Output '::endgroup::'

        Write-Output '::group::Install-Module -Name GitHub -Verbose -Force'
        Install-Module -Name GitHub -Verbose -Force
        Write-Output '::endgroup::'

        Write-Output '::group::Get-GitHubConfig'
        Get-GitHubConfig
        Write-Output '::endgroup::'

        Write-Output '::group::Get-GitHubWorkflow -Repo $env:GITHUB_REPOSITORY_NAME -Owner $env:GITHUB_REPOSITORY_OWNER -Verbose'
        Get-GitHubWorkflow -Repo $env:GITHUB_REPOSITORY_NAME -Owner $env:GITHUB_REPOSITORY_OWNER -Verbose
        Write-Output '::endgroup::'

    - name: Test Authentication using Specific PAT
      if: always()
      shell: pwsh
      run: |
        Write-Output '::group::[Debug info] - Environment variables'
          $env:GITHUB_REPOSITORY_NAME = $env:GITHUB_REPOSITORY.Split('/')[1]
          Get-ChildItem Env:
        Write-Output '::endgroup::'

        Write-Output '::group::[Debug info] - File structure'
          Write-Verbose "Current directory: $((Get-Location).Path)" -Verbose
          Write-Verbose "------------------------------------" -Verbose
          Write-Verbose "Current directory content:" -Verbose
          Get-ChildItem -Path . -Recurse | Select-Object -ExpandProperty FullName | Sort-Object
        Write-Output '::endgroup::'

        Write-Output '::group::Install-Module -Name GitHub -Verbose -Force'
          Install-Module -Name GitHub -Verbose -Force
        Write-Output '::endgroup::'

        Write-Output '::group::Get-GitHubConfig'
          Get-GitHubConfig
        Write-Output '::endgroup::'

        Write-Output '::group::Connect-GitHubAccount -AccessToken $env:GH_TOKEN -Verbose'
          Connect-GitHubAccount -AccessToken $env:GH_TOKEN -Verbose
        Write-Output '::endgroup::'

        Write-Output '::group::Get-GitHubConfig'
          Get-GitHubConfig
        Write-Output '::endgroup::'

        Write-Output '::group::Get-GitHubWorkflow -Repo $env:GITHUB_REPOSITORY_NAME -Owner $env:GITHUB_REPOSITORY_OWNER -Verbose'
          Get-GitHubWorkflow -Repo $env:GITHUB_REPOSITORY_NAME -Owner $env:GITHUB_REPOSITORY_OWNER -Verbose
        Write-Output '::endgroup::'
