name: Update-CoverageReport

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  Update-CoverageReport:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize-PSModule
        uses: PSModule/Initialize-PSModule@v1

      - name: Update-CoverageReport
        uses: PSModule/GitHub-Script@v1
        with:
          Script: . '.\scripts\Update-CoverageReport.ps1'
